#!/usr/bin/env bash

# get the absolute path
pushd $(dirname ${BASH_SOURCE[0]}/../) &> /dev/null
repo_root=$(pwd -P)
popd &> /dev/null

usage() {
  echo "
Usage

  setup/wd [action]

Actions
  install - One-time installation of wd
  upgrade - Updates the repo, installs wd if necessary
  "
}

get_script() {
  curl -s https://raw.github.com/troyxmccall/wd/master/wd > $HOME/.wd
}

symlink_wd() {
  if [[ -e $HOME/.wd ]]; then
    echo "*** Skipping symlink, $HOME/.wd already exists ***"
  else
    ln -s $repo_root/wd $HOME/.wd
  fi
}

wd_hook() {
  echo
  echo '# define the wd function'
  echo "source '$repo_root/wd'"
}

modify_dotfile() {
  if ! grep -q "define the wd function" "$HOME/.bash_profile" ; then
    wd_hook >> $HOME/.bash_profile
  else
    echo
    echo "*** Skipping addition of wd hook. ***"
    echo "Previous installation found in $HOME/.bash_profile"
    echo "Please ensure something like the following is there:"
    echo "--------------------------------------"
    wd_hook
    echo "--------------------------------------"
  fi
}

setup_complete() {
  echo
  echo "*** wd is now set up! ***"
  echo "Please source $HOME/.wd or start a new session to use wd"
}

while [[ $# > 0 ]]; do
  arg="$1"
  shift
  case "x$arg" in
    xinstall)
      get_script && modify_dotfile && setup_complete
    ;;
    xupgrade)
      pushd $repo_root &> /dev/null
      symlink_wd && modify_dotfile && setup_complete
      popd &> /dev/null
    ;;
    xusage)
      usage
      exit 0
    ;;
    *)
      usage
      exit 1
    ;;
  esac
done
